export enum EStateColis {
    A_RECUPERER = "A_RECUPERER",
    EN_TRANSIT = "EN_TRANSIT", 
    ENREGISTRER= "ENREGISTRER",
    A_LIVRER = "A_LIVRER",
    EN_ROUTE = "EN_ROUTE",
    LIVRER = "LIVRER",
    RETOUR_HUB = "RETOUR_HUB",
    RETOUR_ENREGISTRER = "RETOUR_ENREGISTRER",
    RETOUR_EXPEDITEUR = "RETOUR_EXPEDITEUR",
    INTROUVABLE = "INTROUVABLE", 
    NON_LIVRER = "NON_LIVRER",
}
